// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using SiliconStudio.Paradox.Graphics;


#line 1 "C:\Projects\Paradox\samples2\Graphics\DeferredLighting\DeferredLighting\DeferredLighting.Game\Effects\DeferredLightingEffectMain.pdxfx"
using SiliconStudio.Paradox.Effects.Data;

#line 3
namespace DeferredLighting.Effects
{

    #line 5
    public partial class DeferredLightingPrepassEffect  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 7
            context.Mixin(mixin, "ParadoxDefaultLightPrepassEffect");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("DeferredLightingPrepassEffect", new DeferredLightingPrepassEffect());
        }
    }

    #line 10
    public partial class DeferredLightingEffectMain  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 12
            context.Mixin(mixin, "ParadoxDefaultDeferredShader");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("DeferredLightingEffectMain", new DeferredLightingEffectMain());
        }
    }
}
