// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using SiliconStudio.Paradox.Graphics;


#line 1 "C:\Paradox\paradox\samples2\Graphics\SimpleTerrain\SimpleTerrain.Game\Effects\SimpleTerrainEffectMain.pdxfx"
using SiliconStudio.Paradox.Effects.Data;

#line 3
namespace SimpleTerrain.Effects
{

    #line 5
    public partial class SimpleTerrainEffectMain  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 11
            context.Mixin(mixin, "ParadoxDefaultForwardShader");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("SimpleTerrainEffectMain", new SimpleTerrainEffectMain());
        }
    }
}
