// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Xenko.Rendering;
using SiliconStudio.Xenko.Graphics;
using SiliconStudio.Xenko.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Xenko.Graphics.Buffer;

namespace SiliconStudio.Xenko.Rendering
{
    public static partial class VertexTextureTerrainKeys
    {
        public static readonly ParameterKey<SamplerState> MeshTextureSampler = ParameterKeys.New<SamplerState>();
        public static readonly ParameterKey<float> MinimumHeight0 = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> OptimalHeight0 = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> MaximumHeight0 = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> MinimumHeight1 = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> OptimalHeight1 = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> MaximumHeight1 = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> MinimumHeight2 = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> OptimalHeight2 = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> MaximumHeight2 = ParameterKeys.New<float>();
        public static readonly ParameterKey<Texture> MeshTexture0 = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> MeshTexture1 = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> MeshTexture2 = ParameterKeys.New<Texture>();
    }
}
