// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using SiliconStudio.Paradox.Graphics;


#line 1 "C:\Projects\Paradox\samples\Graphics\CubemapReflection\CubemapReflection.Game\Effects\CubemapReflectionEffectMain.pdxfx"
using SiliconStudio.Paradox.Effects.Data;

#line 3
namespace CubemapReflection.Effects
{

    #line 5
    public partial class CubemapReflectionEffectMain  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 7
            context.Mixin(mixin, "ParadoxDefaultDeferredShader");

            #line 8
            context.Mixin(mixin, "EnvironmentMapSpecularDeferredShading");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("CubemapReflectionEffectMain", new CubemapReflectionEffectMain());
        }
    }

    #line 11
    public partial class CubemapReflectionLightingPrepass  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 13
            context.Mixin(mixin, "ParadoxDefaultLightPrepassEffect");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("CubemapReflectionLightingPrepass", new CubemapReflectionLightingPrepass());
        }
    }
}
