// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using SiliconStudio.Paradox.Graphics;


#line 1 "C:\Projects\Paradox\samples2\Graphics\AnimatedModel\AnimatedModel.Game\Effects\AnimatedModelEffectMain.pdxfx"
using SiliconStudio.Paradox.Effects.Data;

#line 3
namespace AnimatedModel.Effects
{

    #line 5
    public partial class AnimatedModelEffectMain  : IShaderMixinBuilder
    {
        public void Generate(ShaderMixinSourceTree mixin, ShaderMixinContext context)
        {

            #line 9
            context.Mixin(mixin, "ParadoxBaseShader");

            #line 11
            context.Mixin(mixin, "SpecularPowerPerMesh");

            #line 13
            context.Mixin(mixin, "BRDFDiffuseBase");

            #line 14
            context.Mixin(mixin, "BRDFSpecularBase");

            #line 15
            context.Mixin(mixin, "LightMultiDirectionalShadingPerPixel", 2);

            #line 17
            if (context.GetParam(MaterialParameters.AlbedoDiffuse) != null)
            {

                {

                    #line 19
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 19
                    context.Mixin(__subMixin, "ComputeBRDFDiffuseLambert");
                    mixin.Mixin.AddComposition("DiffuseLighting", __subMixin.Mixin);
                }

                {

                    #line 20
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 20
                    context.Mixin(__subMixin, context.GetParam(MaterialParameters.AlbedoDiffuse));
                    mixin.Mixin.AddComposition("albedoDiffuse", __subMixin.Mixin);
                }
            }

            #line 22
            if (context.GetParam(MaterialParameters.AlbedoSpecular) != null)
            {

                {

                    #line 24
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 24
                    context.Mixin(__subMixin, "ComputeBRDFColorSpecularBlinnPhong");
                    mixin.Mixin.AddComposition("SpecularLighting", __subMixin.Mixin);
                }

                {

                    #line 25
                    var __subMixin = new ShaderMixinSourceTree() { Parent = mixin };

                    #line 25
                    context.Mixin(__subMixin, context.GetParam(MaterialParameters.AlbedoSpecular));
                    mixin.Mixin.AddComposition("albedoSpecular", __subMixin.Mixin);
                }
            }

            #line 28
            context.Mixin(mixin, "ParadoxSkinning");
        }

        [ModuleInitializer]
        internal static void __Initialize__()

        {
            ShaderMixinManager.Register("AnimatedModelEffectMain", new AnimatedModelEffectMain());
        }
    }
}
